name: Build and deploy Node.js app to Azure Web App - aura-botanica

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B285DC5F816C402590BCAF377171FF4D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_82C48ECE1AEF4E4C91578990B87BB86D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB8BB33617B244FEB2A716A5CF4022FB }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aura-botanica'
          slot-name: 'Production'
          package: .
